#pragma once

#define ROWS 0x10
#define MAX_TEXT_LEN 0x200
#define TEXTBOX_SIZE 0x86
#define MOUSE_STRING_SIZE 0x20
#define MEDIA_STRING_SIZE 0x20
#define NORMAL_KEYS_SIZE 0x67
#define MEDIA_KEYS_SIZE 0x04
#define MOUSE_BUTTONS_SIZE 0x04

#define OTHER_TOKENS_STRING_SIZE 0x46
#define MOUSE_TOKENS_STRING_SIZE 0x2A
#define TOTAL_TOKENS 0x14
#define TOTAL_HOLD_TOKENS 0x03
#define TOTAL_OTHER_TOKENS 0x07
#define TOTAL_MOUSE_TOKENS 0x04

#define WHITESPACE_SIZE 0x0F
